//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CenIT.SSOServices.ServiceSSO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOutTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOutByTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentByIndexUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentBySystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoUserByCookiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListUserByAppodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupSSOByAppcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupPermissionByGroupIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionByAppCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionPermissionByFuntionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionPermissionByFuntionCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByGroupIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentUserByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionsOfUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupSSOByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUserAuthenCationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CService() {
            this.Url = global::CenIT.SSOServices.Properties.Settings.Default.CenIT_SSOServices_ServiceSSO_CService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckUserCompletedEventHandler CheckUserCompleted;
        
        /// <remarks/>
        public event LogOutCompletedEventHandler LogOutCompleted;
        
        /// <remarks/>
        public event LogOutTicketCompletedEventHandler LogOutTicketCompleted;
        
        /// <remarks/>
        public event LogOutByTicketCompletedEventHandler LogOutByTicketCompleted;
        
        /// <remarks/>
        public event CheckUserGroupCompletedEventHandler CheckUserGroupCompleted;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event GetUserInfoByUserNameCompletedEventHandler GetUserInfoByUserNameCompleted;
        
        /// <remarks/>
        public event GetUserInfoByGroupCompletedEventHandler GetUserInfoByGroupCompleted;
        
        /// <remarks/>
        public event GetUserInfoByDepartmentCompletedEventHandler GetUserInfoByDepartmentCompleted;
        
        /// <remarks/>
        public event UpdateUserSessionCompletedEventHandler UpdateUserSessionCompleted;
        
        /// <remarks/>
        public event GetDepartmentByUserCompletedEventHandler GetDepartmentByUserCompleted;
        
        /// <remarks/>
        public event GetDepartmentByIndexUserCompletedEventHandler GetDepartmentByIndexUserCompleted;
        
        /// <remarks/>
        public event GetDepartmentBySystemCompletedEventHandler GetDepartmentBySystemCompleted;
        
        /// <remarks/>
        public event GetDepartmentByIDCompletedEventHandler GetDepartmentByIDCompleted;
        
        /// <remarks/>
        public event GetInfoUserByCookiesCompletedEventHandler GetInfoUserByCookiesCompleted;
        
        /// <remarks/>
        public event GetListUserByAppodeCompletedEventHandler GetListUserByAppodeCompleted;
        
        /// <remarks/>
        public event GetGroupSSOByAppcodeCompletedEventHandler GetGroupSSOByAppcodeCompleted;
        
        /// <remarks/>
        public event GetGroupPermissionByGroupIDCompletedEventHandler GetGroupPermissionByGroupIDCompleted;
        
        /// <remarks/>
        public event GetFunctionByAppCodeCompletedEventHandler GetFunctionByAppCodeCompleted;
        
        /// <remarks/>
        public event GetFunctionPermissionByFuntionIDCompletedEventHandler GetFunctionPermissionByFuntionIDCompleted;
        
        /// <remarks/>
        public event GetFunctionPermissionByFuntionCodeCompletedEventHandler GetFunctionPermissionByFuntionCodeCompleted;
        
        /// <remarks/>
        public event GetUserByGroupIDCompletedEventHandler GetUserByGroupIDCompleted;
        
        /// <remarks/>
        public event GetDepartmentUserByUserNameCompletedEventHandler GetDepartmentUserByUserNameCompleted;
        
        /// <remarks/>
        public event GetFunctionsOfUserCompletedEventHandler GetFunctionsOfUserCompleted;
        
        /// <remarks/>
        public event GetGroupSSOByUsernameCompletedEventHandler GetGroupSSOByUsernameCompleted;
        
        /// <remarks/>
        public event CreateUserAuthenCationCompletedEventHandler CreateUserAuthenCationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CheckUserInfo CheckUser(string sessionID, string userkey, string ticket, string appcode, string permission) {
            object[] results = this.Invoke("CheckUser", new object[] {
                        sessionID,
                        userkey,
                        ticket,
                        appcode,
                        permission});
            return ((CheckUserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserAsync(string sessionID, string userkey, string ticket, string appcode, string permission) {
            this.CheckUserAsync(sessionID, userkey, ticket, appcode, permission, null);
        }
        
        /// <remarks/>
        public void CheckUserAsync(string sessionID, string userkey, string ticket, string appcode, string permission, object userState) {
            if ((this.CheckUserOperationCompleted == null)) {
                this.CheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserOperationCompleted);
            }
            this.InvokeAsync("CheckUser", new object[] {
                        sessionID,
                        userkey,
                        ticket,
                        appcode,
                        permission}, this.CheckUserOperationCompleted, userState);
        }
        
        private void OnCheckUserOperationCompleted(object arg) {
            if ((this.CheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOut(string fStrDomain) {
            this.Invoke("LogOut", new object[] {
                        fStrDomain});
        }
        
        /// <remarks/>
        public void LogOutAsync(string fStrDomain) {
            this.LogOutAsync(fStrDomain, null);
        }
        
        /// <remarks/>
        public void LogOutAsync(string fStrDomain, object userState) {
            if ((this.LogOutOperationCompleted == null)) {
                this.LogOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOutOperationCompleted);
            }
            this.InvokeAsync("LogOut", new object[] {
                        fStrDomain}, this.LogOutOperationCompleted, userState);
        }
        
        private void OnLogOutOperationCompleted(object arg) {
            if ((this.LogOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOutTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOutTicket(string fStrTicket) {
            this.Invoke("LogOutTicket", new object[] {
                        fStrTicket});
        }
        
        /// <remarks/>
        public void LogOutTicketAsync(string fStrTicket) {
            this.LogOutTicketAsync(fStrTicket, null);
        }
        
        /// <remarks/>
        public void LogOutTicketAsync(string fStrTicket, object userState) {
            if ((this.LogOutTicketOperationCompleted == null)) {
                this.LogOutTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOutTicketOperationCompleted);
            }
            this.InvokeAsync("LogOutTicket", new object[] {
                        fStrTicket}, this.LogOutTicketOperationCompleted, userState);
        }
        
        private void OnLogOutTicketOperationCompleted(object arg) {
            if ((this.LogOutTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOutTicketCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOutByTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogOutByTicket(string fStrTicket) {
            object[] results = this.Invoke("LogOutByTicket", new object[] {
                        fStrTicket});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogOutByTicketAsync(string fStrTicket) {
            this.LogOutByTicketAsync(fStrTicket, null);
        }
        
        /// <remarks/>
        public void LogOutByTicketAsync(string fStrTicket, object userState) {
            if ((this.LogOutByTicketOperationCompleted == null)) {
                this.LogOutByTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOutByTicketOperationCompleted);
            }
            this.InvokeAsync("LogOutByTicket", new object[] {
                        fStrTicket}, this.LogOutByTicketOperationCompleted, userState);
        }
        
        private void OnLogOutByTicketOperationCompleted(object arg) {
            if ((this.LogOutByTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOutByTicketCompleted(this, new LogOutByTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUserGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CheckUserInfo CheckUserGroup(string sessionID, string userkey, string ticket, string appcode, string groupcode, string permission) {
            object[] results = this.Invoke("CheckUserGroup", new object[] {
                        sessionID,
                        userkey,
                        ticket,
                        appcode,
                        groupcode,
                        permission});
            return ((CheckUserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserGroupAsync(string sessionID, string userkey, string ticket, string appcode, string groupcode, string permission) {
            this.CheckUserGroupAsync(sessionID, userkey, ticket, appcode, groupcode, permission, null);
        }
        
        /// <remarks/>
        public void CheckUserGroupAsync(string sessionID, string userkey, string ticket, string appcode, string groupcode, string permission, object userState) {
            if ((this.CheckUserGroupOperationCompleted == null)) {
                this.CheckUserGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserGroupOperationCompleted);
            }
            this.InvokeAsync("CheckUserGroup", new object[] {
                        sessionID,
                        userkey,
                        ticket,
                        appcode,
                        groupcode,
                        permission}, this.CheckUserGroupOperationCompleted, userState);
        }
        
        private void OnCheckUserGroupOperationCompleted(object arg) {
            if ((this.CheckUserGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserGroupCompleted(this, new CheckUserGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfo(string sessionID, string userkey, string ticket) {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                        sessionID,
                        userkey,
                        ticket});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string sessionID, string userkey, string ticket) {
            this.GetUserInfoAsync(sessionID, userkey, ticket, null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string sessionID, string userkey, string ticket, object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[] {
                        sessionID,
                        userkey,
                        ticket}, this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUserInfoByUserName(string userName) {
            object[] results = this.Invoke("GetUserInfoByUserName", new object[] {
                        userName});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByUserNameAsync(string userName) {
            this.GetUserInfoByUserNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByUserNameAsync(string userName, object userState) {
            if ((this.GetUserInfoByUserNameOperationCompleted == null)) {
                this.GetUserInfoByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByUserName", new object[] {
                        userName}, this.GetUserInfoByUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByUserNameOperationCompleted(object arg) {
            if ((this.GetUserInfoByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByUserNameCompleted(this, new GetUserInfoByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo[] GetUserInfoByGroup(int groupID) {
            object[] results = this.Invoke("GetUserInfoByGroup", new object[] {
                        groupID});
            return ((UserInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByGroupAsync(int groupID) {
            this.GetUserInfoByGroupAsync(groupID, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByGroupAsync(int groupID, object userState) {
            if ((this.GetUserInfoByGroupOperationCompleted == null)) {
                this.GetUserInfoByGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByGroupOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByGroup", new object[] {
                        groupID}, this.GetUserInfoByGroupOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByGroupOperationCompleted(object arg) {
            if ((this.GetUserInfoByGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByGroupCompleted(this, new GetUserInfoByGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByDepartment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo[] GetUserInfoByDepartment(int departmentID) {
            object[] results = this.Invoke("GetUserInfoByDepartment", new object[] {
                        departmentID});
            return ((UserInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByDepartmentAsync(int departmentID) {
            this.GetUserInfoByDepartmentAsync(departmentID, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByDepartmentAsync(int departmentID, object userState) {
            if ((this.GetUserInfoByDepartmentOperationCompleted == null)) {
                this.GetUserInfoByDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByDepartment", new object[] {
                        departmentID}, this.GetUserInfoByDepartmentOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByDepartmentOperationCompleted(object arg) {
            if ((this.GetUserInfoByDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByDepartmentCompleted(this, new GetUserInfoByDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateUserSession(string sessionID, string userkey, string ticket) {
            object[] results = this.Invoke("UpdateUserSession", new object[] {
                        sessionID,
                        userkey,
                        ticket});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserSessionAsync(string sessionID, string userkey, string ticket) {
            this.UpdateUserSessionAsync(sessionID, userkey, ticket, null);
        }
        
        /// <remarks/>
        public void UpdateUserSessionAsync(string sessionID, string userkey, string ticket, object userState) {
            if ((this.UpdateUserSessionOperationCompleted == null)) {
                this.UpdateUserSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserSessionOperationCompleted);
            }
            this.InvokeAsync("UpdateUserSession", new object[] {
                        sessionID,
                        userkey,
                        ticket}, this.UpdateUserSessionOperationCompleted, userState);
        }
        
        private void OnUpdateUserSessionOperationCompleted(object arg) {
            if ((this.UpdateUserSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserSessionCompleted(this, new UpdateUserSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentInfo[] GetDepartmentByUser(string appcode, string username) {
            object[] results = this.Invoke("GetDepartmentByUser", new object[] {
                        appcode,
                        username});
            return ((DepartmentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentByUserAsync(string appcode, string username) {
            this.GetDepartmentByUserAsync(appcode, username, null);
        }
        
        /// <remarks/>
        public void GetDepartmentByUserAsync(string appcode, string username, object userState) {
            if ((this.GetDepartmentByUserOperationCompleted == null)) {
                this.GetDepartmentByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentByUserOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentByUser", new object[] {
                        appcode,
                        username}, this.GetDepartmentByUserOperationCompleted, userState);
        }
        
        private void OnGetDepartmentByUserOperationCompleted(object arg) {
            if ((this.GetDepartmentByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentByUserCompleted(this, new GetDepartmentByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentByIndexUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentInfo[] GetDepartmentByIndexUser(string appcode, string username, int index) {
            object[] results = this.Invoke("GetDepartmentByIndexUser", new object[] {
                        appcode,
                        username,
                        index});
            return ((DepartmentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentByIndexUserAsync(string appcode, string username, int index) {
            this.GetDepartmentByIndexUserAsync(appcode, username, index, null);
        }
        
        /// <remarks/>
        public void GetDepartmentByIndexUserAsync(string appcode, string username, int index, object userState) {
            if ((this.GetDepartmentByIndexUserOperationCompleted == null)) {
                this.GetDepartmentByIndexUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentByIndexUserOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentByIndexUser", new object[] {
                        appcode,
                        username,
                        index}, this.GetDepartmentByIndexUserOperationCompleted, userState);
        }
        
        private void OnGetDepartmentByIndexUserOperationCompleted(object arg) {
            if ((this.GetDepartmentByIndexUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentByIndexUserCompleted(this, new GetDepartmentByIndexUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentBySystem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentInfo[] GetDepartmentBySystem(string appcode) {
            object[] results = this.Invoke("GetDepartmentBySystem", new object[] {
                        appcode});
            return ((DepartmentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentBySystemAsync(string appcode) {
            this.GetDepartmentBySystemAsync(appcode, null);
        }
        
        /// <remarks/>
        public void GetDepartmentBySystemAsync(string appcode, object userState) {
            if ((this.GetDepartmentBySystemOperationCompleted == null)) {
                this.GetDepartmentBySystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentBySystemOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentBySystem", new object[] {
                        appcode}, this.GetDepartmentBySystemOperationCompleted, userState);
        }
        
        private void OnGetDepartmentBySystemOperationCompleted(object arg) {
            if ((this.GetDepartmentBySystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentBySystemCompleted(this, new GetDepartmentBySystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentInfo GetDepartmentByID(int id) {
            object[] results = this.Invoke("GetDepartmentByID", new object[] {
                        id});
            return ((DepartmentInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentByIDAsync(int id) {
            this.GetDepartmentByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDepartmentByIDAsync(int id, object userState) {
            if ((this.GetDepartmentByIDOperationCompleted == null)) {
                this.GetDepartmentByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentByIDOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentByID", new object[] {
                        id}, this.GetDepartmentByIDOperationCompleted, userState);
        }
        
        private void OnGetDepartmentByIDOperationCompleted(object arg) {
            if ((this.GetDepartmentByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentByIDCompleted(this, new GetDepartmentByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoUserByCookies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUserByCookies GetInfoUserByCookies() {
            object[] results = this.Invoke("GetInfoUserByCookies", new object[0]);
            return ((GetUserByCookies)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoUserByCookiesAsync() {
            this.GetInfoUserByCookiesAsync(null);
        }
        
        /// <remarks/>
        public void GetInfoUserByCookiesAsync(object userState) {
            if ((this.GetInfoUserByCookiesOperationCompleted == null)) {
                this.GetInfoUserByCookiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoUserByCookiesOperationCompleted);
            }
            this.InvokeAsync("GetInfoUserByCookies", new object[0], this.GetInfoUserByCookiesOperationCompleted, userState);
        }
        
        private void OnGetInfoUserByCookiesOperationCompleted(object arg) {
            if ((this.GetInfoUserByCookiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoUserByCookiesCompleted(this, new GetInfoUserByCookiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListUserByAppode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetListUserByAppode(UserAuthenCationHeader UserAuthenCation) {
            object[] results = this.Invoke("GetListUserByAppode", new object[] {
                        UserAuthenCation});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetListUserByAppodeAsync(UserAuthenCationHeader UserAuthenCation) {
            this.GetListUserByAppodeAsync(UserAuthenCation, null);
        }
        
        /// <remarks/>
        public void GetListUserByAppodeAsync(UserAuthenCationHeader UserAuthenCation, object userState) {
            if ((this.GetListUserByAppodeOperationCompleted == null)) {
                this.GetListUserByAppodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListUserByAppodeOperationCompleted);
            }
            this.InvokeAsync("GetListUserByAppode", new object[] {
                        UserAuthenCation}, this.GetListUserByAppodeOperationCompleted, userState);
        }
        
        private void OnGetListUserByAppodeOperationCompleted(object arg) {
            if ((this.GetListUserByAppodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListUserByAppodeCompleted(this, new GetListUserByAppodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupSSOByAppcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetGroupSSOByAppcode(UserAuthenCationHeader UserAuthenCation) {
            object[] results = this.Invoke("GetGroupSSOByAppcode", new object[] {
                        UserAuthenCation});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupSSOByAppcodeAsync(UserAuthenCationHeader UserAuthenCation) {
            this.GetGroupSSOByAppcodeAsync(UserAuthenCation, null);
        }
        
        /// <remarks/>
        public void GetGroupSSOByAppcodeAsync(UserAuthenCationHeader UserAuthenCation, object userState) {
            if ((this.GetGroupSSOByAppcodeOperationCompleted == null)) {
                this.GetGroupSSOByAppcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupSSOByAppcodeOperationCompleted);
            }
            this.InvokeAsync("GetGroupSSOByAppcode", new object[] {
                        UserAuthenCation}, this.GetGroupSSOByAppcodeOperationCompleted, userState);
        }
        
        private void OnGetGroupSSOByAppcodeOperationCompleted(object arg) {
            if ((this.GetGroupSSOByAppcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupSSOByAppcodeCompleted(this, new GetGroupSSOByAppcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupPermissionByGroupID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetGroupPermissionByGroupID(UserAuthenCationHeader UserAuthenCation, int aGroupID) {
            object[] results = this.Invoke("GetGroupPermissionByGroupID", new object[] {
                        UserAuthenCation,
                        aGroupID});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupPermissionByGroupIDAsync(UserAuthenCationHeader UserAuthenCation, int aGroupID) {
            this.GetGroupPermissionByGroupIDAsync(UserAuthenCation, aGroupID, null);
        }
        
        /// <remarks/>
        public void GetGroupPermissionByGroupIDAsync(UserAuthenCationHeader UserAuthenCation, int aGroupID, object userState) {
            if ((this.GetGroupPermissionByGroupIDOperationCompleted == null)) {
                this.GetGroupPermissionByGroupIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupPermissionByGroupIDOperationCompleted);
            }
            this.InvokeAsync("GetGroupPermissionByGroupID", new object[] {
                        UserAuthenCation,
                        aGroupID}, this.GetGroupPermissionByGroupIDOperationCompleted, userState);
        }
        
        private void OnGetGroupPermissionByGroupIDOperationCompleted(object arg) {
            if ((this.GetGroupPermissionByGroupIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupPermissionByGroupIDCompleted(this, new GetGroupPermissionByGroupIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFunctionByAppCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetFunctionByAppCode(UserAuthenCationHeader UserAuthenCation) {
            object[] results = this.Invoke("GetFunctionByAppCode", new object[] {
                        UserAuthenCation});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionByAppCodeAsync(UserAuthenCationHeader UserAuthenCation) {
            this.GetFunctionByAppCodeAsync(UserAuthenCation, null);
        }
        
        /// <remarks/>
        public void GetFunctionByAppCodeAsync(UserAuthenCationHeader UserAuthenCation, object userState) {
            if ((this.GetFunctionByAppCodeOperationCompleted == null)) {
                this.GetFunctionByAppCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionByAppCodeOperationCompleted);
            }
            this.InvokeAsync("GetFunctionByAppCode", new object[] {
                        UserAuthenCation}, this.GetFunctionByAppCodeOperationCompleted, userState);
        }
        
        private void OnGetFunctionByAppCodeOperationCompleted(object arg) {
            if ((this.GetFunctionByAppCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionByAppCodeCompleted(this, new GetFunctionByAppCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFunctionPermissionByFuntionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetFunctionPermissionByFuntionID(UserAuthenCationHeader UserAuthenCation, int aFuntionID) {
            object[] results = this.Invoke("GetFunctionPermissionByFuntionID", new object[] {
                        UserAuthenCation,
                        aFuntionID});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionPermissionByFuntionIDAsync(UserAuthenCationHeader UserAuthenCation, int aFuntionID) {
            this.GetFunctionPermissionByFuntionIDAsync(UserAuthenCation, aFuntionID, null);
        }
        
        /// <remarks/>
        public void GetFunctionPermissionByFuntionIDAsync(UserAuthenCationHeader UserAuthenCation, int aFuntionID, object userState) {
            if ((this.GetFunctionPermissionByFuntionIDOperationCompleted == null)) {
                this.GetFunctionPermissionByFuntionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionPermissionByFuntionIDOperationCompleted);
            }
            this.InvokeAsync("GetFunctionPermissionByFuntionID", new object[] {
                        UserAuthenCation,
                        aFuntionID}, this.GetFunctionPermissionByFuntionIDOperationCompleted, userState);
        }
        
        private void OnGetFunctionPermissionByFuntionIDOperationCompleted(object arg) {
            if ((this.GetFunctionPermissionByFuntionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionPermissionByFuntionIDCompleted(this, new GetFunctionPermissionByFuntionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFunctionPermissionByFuntionCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetFunctionPermissionByFuntionCode(UserAuthenCationHeader UserAuthenCation, string aFuntionCode) {
            object[] results = this.Invoke("GetFunctionPermissionByFuntionCode", new object[] {
                        UserAuthenCation,
                        aFuntionCode});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionPermissionByFuntionCodeAsync(UserAuthenCationHeader UserAuthenCation, string aFuntionCode) {
            this.GetFunctionPermissionByFuntionCodeAsync(UserAuthenCation, aFuntionCode, null);
        }
        
        /// <remarks/>
        public void GetFunctionPermissionByFuntionCodeAsync(UserAuthenCationHeader UserAuthenCation, string aFuntionCode, object userState) {
            if ((this.GetFunctionPermissionByFuntionCodeOperationCompleted == null)) {
                this.GetFunctionPermissionByFuntionCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionPermissionByFuntionCodeOperationCompleted);
            }
            this.InvokeAsync("GetFunctionPermissionByFuntionCode", new object[] {
                        UserAuthenCation,
                        aFuntionCode}, this.GetFunctionPermissionByFuntionCodeOperationCompleted, userState);
        }
        
        private void OnGetFunctionPermissionByFuntionCodeOperationCompleted(object arg) {
            if ((this.GetFunctionPermissionByFuntionCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionPermissionByFuntionCodeCompleted(this, new GetFunctionPermissionByFuntionCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByGroupID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetUserByGroupID(UserAuthenCationHeader UserAuthenCation, int aGroupID) {
            object[] results = this.Invoke("GetUserByGroupID", new object[] {
                        UserAuthenCation,
                        aGroupID});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByGroupIDAsync(UserAuthenCationHeader UserAuthenCation, int aGroupID) {
            this.GetUserByGroupIDAsync(UserAuthenCation, aGroupID, null);
        }
        
        /// <remarks/>
        public void GetUserByGroupIDAsync(UserAuthenCationHeader UserAuthenCation, int aGroupID, object userState) {
            if ((this.GetUserByGroupIDOperationCompleted == null)) {
                this.GetUserByGroupIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByGroupIDOperationCompleted);
            }
            this.InvokeAsync("GetUserByGroupID", new object[] {
                        UserAuthenCation,
                        aGroupID}, this.GetUserByGroupIDOperationCompleted, userState);
        }
        
        private void OnGetUserByGroupIDOperationCompleted(object arg) {
            if ((this.GetUserByGroupIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByGroupIDCompleted(this, new GetUserByGroupIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentUserByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetDepartmentUserByUserName(UserAuthenCationHeader UserAuthenCation, string Username) {
            object[] results = this.Invoke("GetDepartmentUserByUserName", new object[] {
                        UserAuthenCation,
                        Username});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentUserByUserNameAsync(UserAuthenCationHeader UserAuthenCation, string Username) {
            this.GetDepartmentUserByUserNameAsync(UserAuthenCation, Username, null);
        }
        
        /// <remarks/>
        public void GetDepartmentUserByUserNameAsync(UserAuthenCationHeader UserAuthenCation, string Username, object userState) {
            if ((this.GetDepartmentUserByUserNameOperationCompleted == null)) {
                this.GetDepartmentUserByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentUserByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentUserByUserName", new object[] {
                        UserAuthenCation,
                        Username}, this.GetDepartmentUserByUserNameOperationCompleted, userState);
        }
        
        private void OnGetDepartmentUserByUserNameOperationCompleted(object arg) {
            if ((this.GetDepartmentUserByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentUserByUserNameCompleted(this, new GetDepartmentUserByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFunctionsOfUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetFunctionsOfUser(UserAuthenCationHeader UserAuthenCation) {
            object[] results = this.Invoke("GetFunctionsOfUser", new object[] {
                        UserAuthenCation});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionsOfUserAsync(UserAuthenCationHeader UserAuthenCation) {
            this.GetFunctionsOfUserAsync(UserAuthenCation, null);
        }
        
        /// <remarks/>
        public void GetFunctionsOfUserAsync(UserAuthenCationHeader UserAuthenCation, object userState) {
            if ((this.GetFunctionsOfUserOperationCompleted == null)) {
                this.GetFunctionsOfUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionsOfUserOperationCompleted);
            }
            this.InvokeAsync("GetFunctionsOfUser", new object[] {
                        UserAuthenCation}, this.GetFunctionsOfUserOperationCompleted, userState);
        }
        
        private void OnGetFunctionsOfUserOperationCompleted(object arg) {
            if ((this.GetFunctionsOfUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionsOfUserCompleted(this, new GetFunctionsOfUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupSSOByUsername", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultServices GetGroupSSOByUsername(UserAuthenCationHeader UserAuthenCation, string Username) {
            object[] results = this.Invoke("GetGroupSSOByUsername", new object[] {
                        UserAuthenCation,
                        Username});
            return ((ResultServices)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupSSOByUsernameAsync(UserAuthenCationHeader UserAuthenCation, string Username) {
            this.GetGroupSSOByUsernameAsync(UserAuthenCation, Username, null);
        }
        
        /// <remarks/>
        public void GetGroupSSOByUsernameAsync(UserAuthenCationHeader UserAuthenCation, string Username, object userState) {
            if ((this.GetGroupSSOByUsernameOperationCompleted == null)) {
                this.GetGroupSSOByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupSSOByUsernameOperationCompleted);
            }
            this.InvokeAsync("GetGroupSSOByUsername", new object[] {
                        UserAuthenCation,
                        Username}, this.GetGroupSSOByUsernameOperationCompleted, userState);
        }
        
        private void OnGetGroupSSOByUsernameOperationCompleted(object arg) {
            if ((this.GetGroupSSOByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupSSOByUsernameCompleted(this, new GetGroupSSOByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUserAuthenCation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAuthenCationHeader CreateUserAuthenCation() {
            object[] results = this.Invoke("CreateUserAuthenCation", new object[0]);
            return ((UserAuthenCationHeader)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAuthenCationAsync() {
            this.CreateUserAuthenCationAsync(null);
        }
        
        /// <remarks/>
        public void CreateUserAuthenCationAsync(object userState) {
            if ((this.CreateUserAuthenCationOperationCompleted == null)) {
                this.CreateUserAuthenCationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserAuthenCationOperationCompleted);
            }
            this.InvokeAsync("CreateUserAuthenCation", new object[0], this.CreateUserAuthenCationOperationCompleted, userState);
        }
        
        private void OnCreateUserAuthenCationOperationCompleted(object arg) {
            if ((this.CreateUserAuthenCationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserAuthenCationCompleted(this, new CreateUserAuthenCationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserInfo {
        
        private int validField;
        
        private string globalusernameField;
        
        private string thesaltField;
        
        private string globalusernamehashField;
        
        private int permissionField;
        
        //10042021 fix loi dang nhap
        public string Email_VNPTKhanhHoa { get; set; }
        /// <remarks/>
        public int valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string globalusername {
            get {
                return this.globalusernameField;
            }
            set {
                this.globalusernameField = value;
            }
        }
        
        /// <remarks/>
        public string thesalt {
            get {
                return this.thesaltField;
            }
            set {
                this.thesaltField = value;
            }
        }
        
        /// <remarks/>
        public string globalusernamehash {
            get {
                return this.globalusernamehashField;
            }
            set {
                this.globalusernamehashField = value;
            }
        }
        
        /// <remarks/>
        public int permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultServices {
        
        private int statusField;
        
        private string messageField;
        
        private System.Data.DataTable dataField;
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenCationHeader {
        
        private string sessionIDField;
        
        private string userkeyField;
        
        private string ticketField;
        
        private string appCodeField;
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public string Userkey {
            get {
                return this.userkeyField;
            }
            set {
                this.userkeyField = value;
            }
        }
        
        /// <remarks/>
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        public string AppCode {
            get {
                return this.appCodeField;
            }
            set {
                this.appCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByCookies {
        
        private string ticketField;
        
        private string userNameField;
        
        private string fullNameField;
        
        private string fullName2Field;
        
        /// <remarks/>
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName2 {
            get {
                return this.fullName2Field;
            }
            set {
                this.fullName2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmentInfo {
        
        private int idField;
        
        private string nameField;
        
        private string codeField;
        
        private int indexField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo {
        
        private string usernameField;
        
        private string fullnameField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckUserCompletedEventHandler(object sender, CheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckUserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckUserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogOutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogOutTicketCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogOutByTicketCompletedEventHandler(object sender, LogOutByTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogOutByTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogOutByTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckUserGroupCompletedEventHandler(object sender, CheckUserGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckUserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckUserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetUserInfoByUserNameCompletedEventHandler(object sender, GetUserInfoByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetUserInfoByGroupCompletedEventHandler(object sender, GetUserInfoByGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetUserInfoByDepartmentCompletedEventHandler(object sender, GetUserInfoByDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateUserSessionCompletedEventHandler(object sender, UpdateUserSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentByUserCompletedEventHandler(object sender, GetDepartmentByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentByIndexUserCompletedEventHandler(object sender, GetDepartmentByIndexUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentByIndexUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentByIndexUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentBySystemCompletedEventHandler(object sender, GetDepartmentBySystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentBySystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentBySystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentByIDCompletedEventHandler(object sender, GetDepartmentByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetInfoUserByCookiesCompletedEventHandler(object sender, GetInfoUserByCookiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoUserByCookiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoUserByCookiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserByCookies Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserByCookies)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListUserByAppodeCompletedEventHandler(object sender, GetListUserByAppodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListUserByAppodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListUserByAppodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGroupSSOByAppcodeCompletedEventHandler(object sender, GetGroupSSOByAppcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupSSOByAppcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupSSOByAppcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGroupPermissionByGroupIDCompletedEventHandler(object sender, GetGroupPermissionByGroupIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupPermissionByGroupIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupPermissionByGroupIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFunctionByAppCodeCompletedEventHandler(object sender, GetFunctionByAppCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionByAppCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionByAppCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFunctionPermissionByFuntionIDCompletedEventHandler(object sender, GetFunctionPermissionByFuntionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionPermissionByFuntionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionPermissionByFuntionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFunctionPermissionByFuntionCodeCompletedEventHandler(object sender, GetFunctionPermissionByFuntionCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionPermissionByFuntionCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionPermissionByFuntionCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetUserByGroupIDCompletedEventHandler(object sender, GetUserByGroupIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByGroupIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByGroupIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentUserByUserNameCompletedEventHandler(object sender, GetDepartmentUserByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentUserByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentUserByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFunctionsOfUserCompletedEventHandler(object sender, GetFunctionsOfUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionsOfUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionsOfUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGroupSSOByUsernameCompletedEventHandler(object sender, GetGroupSSOByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupSSOByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupSSOByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultServices Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultServices)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateUserAuthenCationCompletedEventHandler(object sender, CreateUserAuthenCationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserAuthenCationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserAuthenCationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAuthenCationHeader Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAuthenCationHeader)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591