//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenIT.Libs.HDDT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string CenIT_Libs_HDDT_InvoiceBusinessService_BusinessService {
            get {
                return ((string)(this["CenIT_Libs_HDDT_InvoiceBusinessService_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string CenIT_Libs_HDDT_InvoicePublishService_PublishService {
            get {
                return ((string)(this["CenIT_Libs_HDDT_InvoicePublishService_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string CenIT_Libs_HDDT_InvoicePortalService_PortalService {
            get {
                return ((string)(this["CenIT_Libs_HDDT_InvoicePortalService_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string CenIT_Libs_EInvoice_InvoiceBusinessService_BusinessService {
            get {
                return ((string)(this["CenIT_Libs_EInvoice_InvoiceBusinessService_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/PortalService.asmx")]
        public string CenIT_Libs_EInvoice_InvoicePortalService_PortalService {
            get {
                return ((string)(this["CenIT_Libs_EInvoice_InvoicePortalService_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dothidalatadmindemo.vnpt-invoice.com.vn/PublishService.asmx")]
        public string CenIT_Libs_EInvoice_InvoicePublishService_PublishService {
            get {
                return ((string)(this["CenIT_Libs_EInvoice_InvoicePublishService_PublishService"]));
            }
        }
    }
}
